import { defineToolcraft } from "@/toolcraft/runtime";

import { getAutomaticDurationMs } from "../audio/audio-engine";
import { createDefaultSoundPack, CUELUME_PRESET_IDS } from "../audio/presets";
import { createEditorSnapshot, targets } from "./editor-model";

export const defaultSoundPack = createDefaultSoundPack();
const editorDefaults = createEditorSnapshot(defaultSoundPack);
export const DEFAULT_TIMELINE_DURATION_SECONDS =
  getAutomaticDurationMs(defaultSoundPack.sounds[0]) / 1_000;

const responsivenessReason =
  "The control updates the procedural waveform preview and must remain responsive during editing.";

export const appSchema = defineToolcraft({
  canvas: {
    draggable: false,
    enabled: true,
    renderScale: false,
    size: { height: 1_200, unit: "px", width: 1_920 },
    sizing: { mode: "fixed-output" },
    upload: false,
  },
  panels: {
    controls: {
      sections: [
        {
          controls: {
            packName: {
              commitMode: "content",
              defaultValue: editorDefaults[targets.packName],
              label: "Pack name",
              orderRole: "primary",
              performanceReason: responsivenessReason,
              performanceRole: "responsiveness",
              target: targets.packName,
              textValueKind: "single-line",
              type: "text",
            },
            cueLibrary: {
              defaultValue: defaultSoundPack,
              label: "Cues",
              orderRole: "primary",
              performanceReason:
                "Selecting, ordering, duplicating, or removing a cue changes the active procedural output.",
              performanceRole: "responsiveness",
              target: targets.pack,
              type: "cueLibrary",
            },
            cueName: {
              commitMode: "content",
              defaultValue: editorDefaults[targets.cueName],
              label: "Cue name",
              orderRole: "input",
              performanceReason: responsivenessReason,
              performanceRole: "responsiveness",
              target: targets.cueName,
              textValueKind: "single-line",
              type: "text",
            },
          },
          title: "Sound Pack",
        },
        {
          controls: {
            preset: {
              defaultValue: "success",
              label: "Cuelume preset",
              options: CUELUME_PRESET_IDS.map((presetId) => ({
                label: presetId[0].toUpperCase() + presetId.slice(1), value: presetId,
              })),
              orderRole: "mode",
              performanceReason: responsivenessReason,
              performanceRole: "responsiveness",
              target: targets.presetId,
              type: "select",
            },
            variationSeed: {
              defaultValue: 42,
              label: "Seed",
              max: 9_999,
              min: 0,
              orderRole: "detail",
              performanceReason: responsivenessReason,
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: targets.variationSeed,
              type: "slider",
            },
            variationIntensity: {
              defaultValue: 50,
              label: "Variation intensity",
              max: 100,
              min: 0,
              orderRole: "strength",
              performanceReason: responsivenessReason,
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: targets.variationIntensity,
              type: "slider",
              unit: "%",
            },
            presetActions: {
              actions: [
                { icon: "shuffle", label: "Randomize", value: "variation.randomize" },
              ],
              label: "Create cue",
              orderRole: "action",
              performanceReason:
                "Applying a preset or creating a variation renders a new procedural cue.",
              performanceRole: "responsiveness",
              target: "actions.preset",
              type: "actions",
            },
          },
          title: "Presets & Variations",
        },
        {
          controls: {
            layerStack: {
              defaultValue: editorDefaults[targets.selectedLayerId],
              label: "Synthesis layers",
              orderRole: "primary",
              performanceReason:
                "Layer selection, visibility, ordering, creation, and deletion all change the rendered cue.",
              performanceRole: "responsiveness",
              target: targets.selectedLayerId,
              type: "layerStack",
            },
            layerName: {
              commitMode: "content",
              defaultValue: editorDefaults[targets.layerName],
              label: "Layer name",
              orderRole: "input",
              performanceReason: responsivenessReason,
              performanceRole: "responsiveness",
              target: targets.layerName,
              textValueKind: "single-line",
              type: "text",
            },
          },
          title: "Layers",
        },
        {
          controls: {
            start: {
              defaultValue: editorDefaults[targets.layerStartMs],
              label: "Offset",
              max: 5_000,
              min: 0,
              orderRole: "spatial",
              performanceReason: responsivenessReason,
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: targets.layerStartMs,
              type: "slider",
              unit: "ms",
            },
            attack: {
              defaultValue: editorDefaults[targets.layerAttackMs],
              label: "Attack",
              max: 1_000,
              min: 0,
              orderRole: "detail",
              performanceReason: responsivenessReason,
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: targets.layerAttackMs,
              type: "slider",
              unit: "ms",
            },
            decay: {
              defaultValue: editorDefaults[targets.layerDecayMs],
              label: "Decay",
              max: 5_000,
              min: 1,
              orderRole: "detail",
              performanceReason: responsivenessReason,
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: targets.layerDecayMs,
              type: "slider",
              unit: "ms",
            },
          },
          title: "Layer Timing",
        },
        {
          controls: {
            waveform: {
              defaultValue: editorDefaults[targets.layerWaveform],
              label: "Waveform",
              options: [
                { label: "Sine", value: "sine" },
                { label: "Triangle", value: "triangle" },
                { label: "Square", value: "square" },
                { label: "Sawtooth", value: "sawtooth" },
              ],
              orderRole: "mode",
              performanceReason: responsivenessReason,
              performanceRole: "responsiveness",
              target: targets.layerWaveform,
              type: "select",
            },
            frequency: {
              defaultValue: editorDefaults[targets.layerFrequencyHz],
              label: "Frequency",
              max: 20_000,
              min: 20,
              orderRole: "primary",
              performanceReason: responsivenessReason,
              performanceRole: "responsiveness",
              step: 0.01,
              target: targets.layerFrequencyHz,
              type: "logSlider",
              unit: "Hz",
            },
            detune: {
              defaultValue: editorDefaults[targets.layerDetuneCents],
              label: "Detune",
              max: 1_200,
              min: -1_200,
              orderRole: "detail",
              performanceReason: responsivenessReason,
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: targets.layerDetuneCents,
              type: "slider",
              unit: "ct",
            },
            glide: {
              defaultValue: editorDefaults[targets.layerGlideEnabled],
              label: "Pitch glide",
              orderRole: "mode",
              performanceReason: responsivenessReason,
              performanceRole: "responsiveness",
              target: targets.layerGlideEnabled,
              type: "switch",
            },
            glideTo: {
              defaultValue: editorDefaults[targets.layerGlideToHz],
              label: "Glide to",
              max: 20_000,
              min: 20,
              orderRole: "primary",
              performanceReason: responsivenessReason,
              performanceRole: "responsiveness",
              step: 0.01,
              target: targets.layerGlideToHz,
              type: "logSlider",
              unit: "Hz",
            },
            glideDuration: {
              defaultValue: editorDefaults[targets.layerGlideDurationMs],
              label: "Glide time",
              max: 5_000,
              min: 1,
              orderRole: "detail",
              performanceReason: responsivenessReason,
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: targets.layerGlideDurationMs,
              type: "slider",
              unit: "ms",
            },
          },
          title: "Tone",
          visibleWhen: { equals: "tone", target: targets.layerKind },
        },
        {
          controls: {
            filterType: {
              defaultValue: editorDefaults[targets.layerFilterType],
              label: "Filter",
              options: [
                { label: "Low-pass", value: "lowpass" },
                { label: "Band-pass", value: "bandpass" },
                { label: "High-pass", value: "highpass" },
              ],
              orderRole: "mode",
              performanceReason: responsivenessReason,
              performanceRole: "responsiveness",
              target: targets.layerFilterType,
              type: "select",
            },
            cutoff: {
              defaultValue: editorDefaults[targets.layerFilterCutoffHz],
              label: "Cutoff",
              max: 20_000,
              min: 20,
              orderRole: "primary",
              performanceReason: responsivenessReason,
              performanceRole: "responsiveness",
              step: 0.01,
              target: targets.layerFilterCutoffHz,
              type: "logSlider",
              unit: "Hz",
            },
            filterQ: {
              defaultValue: editorDefaults[targets.layerFilterQ],
              label: "Resonance",
              max: 30,
              min: 0.1,
              orderRole: "detail",
              performanceReason: responsivenessReason,
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 0.1,
              target: targets.layerFilterQ,
              type: "slider",
            },
          },
          title: "Noise",
          visibleWhen: { equals: "noise", target: targets.layerKind },
        },
        {
          controls: {
            gain: {
              defaultValue: editorDefaults[targets.layerGainDb],
              label: "Gain",
              max: 6,
              min: -60,
              orderRole: "strength",
              performanceReason: responsivenessReason,
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 0.1,
              target: targets.layerGainDb,
              type: "slider",
              unit: "dB",
            },
            pan: {
              defaultValue: editorDefaults[targets.layerPan],
              label: "Pan",
              max: 1,
              min: -1,
              orderRole: "spatial",
              performanceReason: responsivenessReason,
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 0.01,
              target: targets.layerPan,
              type: "slider",
            },
          },
          title: "Layer Level",
        },
        {
          controls: {
            masterGain: {
              defaultValue: editorDefaults[targets.masterGainDb],
              label: "Master gain",
              max: 6,
              min: -60,
              orderRole: "strength",
              performanceReason: responsivenessReason,
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 0.1,
              target: targets.masterGainDb,
              type: "slider",
              unit: "dB",
            },
            shimmer: {
              defaultValue: editorDefaults[targets.shimmerEnabled],
              label: "Shimmer",
              orderRole: "mode",
              performanceReason: responsivenessReason,
              performanceRole: "responsiveness",
              target: targets.shimmerEnabled,
              type: "switch",
            },
            shimmerWet: {
              defaultValue: editorDefaults[targets.shimmerWet],
              label: "Wet",
              max: 1,
              min: 0,
              orderRole: "strength",
              performanceReason: responsivenessReason,
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 0.01,
              target: targets.shimmerWet,
              type: "slider",
            },
            shimmerDelay: {
              defaultValue: editorDefaults[targets.shimmerDelayMs],
              label: "Delay",
              max: 2_000,
              min: 1,
              orderRole: "detail",
              performanceReason: responsivenessReason,
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: targets.shimmerDelayMs,
              type: "slider",
              unit: "ms",
            },
            shimmerFeedback: {
              defaultValue: editorDefaults[targets.shimmerFeedback],
              label: "Feedback",
              max: 0.95,
              min: 0,
              orderRole: "detail",
              performanceReason: responsivenessReason,
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 0.01,
              target: targets.shimmerFeedback,
              type: "slider",
            },
            shimmerLowpass: {
              defaultValue: editorDefaults[targets.shimmerLowpassHz],
              label: "Tone",
              max: 20_000,
              min: 20,
              orderRole: "detail",
              performanceReason: responsivenessReason,
              performanceRole: "responsiveness",
              step: 0.01,
              target: targets.shimmerLowpassHz,
              type: "logSlider",
              unit: "Hz",
            },
          },
          title: "Master & Shimmer",
        },
        {
          controls: {
            durationMode: {
              defaultValue: editorDefaults[targets.durationMode],
              label: "Duration",
              options: [
                { label: "Auto", value: "auto" },
                { label: "Trim", value: "trim" },
              ],
              orderRole: "mode",
              performanceReason: responsivenessReason,
              performanceRole: "responsiveness",
              target: targets.durationMode,
              type: "segmented",
            },
            trimEnd: {
              defaultValue: editorDefaults[targets.trimEndMs],
              label: "End",
              max: 5_000,
              min: 10,
              orderRole: "detail",
              performanceReason: responsivenessReason,
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: targets.trimEndMs,
              type: "slider",
              unit: "ms",
            },
            trimSilence: {
              defaultValue: editorDefaults[targets.trimSilence],
              label: "Trim silence",
              orderRole: "mode",
              performanceReason: responsivenessReason,
              performanceRole: "responsiveness",
              target: targets.trimSilence,
              type: "switch",
            },
            fadeIn: {
              defaultValue: editorDefaults[targets.fadeInMs],
              label: "Fade in",
              max: 500,
              min: 0,
              orderRole: "detail",
              performanceReason: responsivenessReason,
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: targets.fadeInMs,
              type: "slider",
              unit: "ms",
            },
            fadeOut: {
              defaultValue: editorDefaults[targets.fadeOutMs],
              label: "Fade out",
              max: 1_000,
              min: 0,
              orderRole: "detail",
              performanceReason: responsivenessReason,
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: targets.fadeOutMs,
              type: "slider",
              unit: "ms",
            },
            normalize: {
              defaultValue: editorDefaults[targets.normalize],
              label: "Normalize",
              orderRole: "mode",
              performanceReason: responsivenessReason,
              performanceRole: "responsiveness",
              target: targets.normalize,
              type: "switch",
            },
            targetPeak: {
              defaultValue: editorDefaults[targets.targetPeakDbfs],
              label: "Target peak",
              max: 0,
              min: -36,
              orderRole: "strength",
              performanceReason: responsivenessReason,
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 0.5,
              target: targets.targetPeakDbfs,
              type: "slider",
              unit: "dBFS",
            },
          },
          title: "Trim & Mastering",
        },
        {
          controls: {
            sampleRate: {
              defaultValue: String(editorDefaults[targets.sampleRate]),
              label: "Sample rate",
              options: [{ label: "44.1 kHz", value: "44100" }, { label: "48 kHz", value: "48000" }],
              orderRole: "mode",
              performanceReason: "Changes render resolution and WAV byte output.",
              performanceRole: "workload",
              target: targets.sampleRate,
              type: "select",
            },
            bitDepth: {
              defaultValue: String(editorDefaults[targets.bitDepth]),
              label: "Bit depth",
              options: [{ label: "16-bit", value: "16" }, { label: "24-bit", value: "24" }],
              orderRole: "mode",
              performanceReason: "Changes WAV encoding size and precision.",
              performanceRole: "responsiveness",
              target: targets.bitDepth,
              type: "select",
            },
            channels: {
              defaultValue: String(editorDefaults[targets.channels]),
              label: "Channels",
              options: [{ label: "Mono", value: "1" }, { label: "Stereo", value: "2" }],
              orderRole: "mode",
              performanceReason: "Stereo doubles rendered and encoded channel data.",
              performanceRole: "workload",
              target: targets.channels,
              type: "select",
            },
          },
          title: "Audio Export",
        },
        {
          controls: {
            outputActions: {
              actions: [
                { icon: "download", label: "Export WAV", role: "download-output", value: "export.wav" },
                { icon: "download-simple", label: "Export Recipe", role: "download-output", value: "export.recipe" },
                { icon: "download", label: "Export Pack ZIP", role: "download-output", value: "export.pack" },
              ],
              orderRole: "action",
              target: "actions.output",
              type: "panelActions",
            },
          },
        },
      ],
      title: "Inspector",
    },
    timeline: {
      defaultDurationSeconds: DEFAULT_TIMELINE_DURATION_SECONDS,
      enabled: true,
      mode: "playback",
    },
  },
  persistence: {
    include: ["values", "panels", "timeline"],
    // Keep the legacy key so workspaces created before the Rabi Sound rename survive reload.
    key: "toolcraft:cuelume-studio:state:v1",
    storage: "localStorage",
    version: 1,
  },
  settingsTransfer: {
    appId: "rabi-sound",
    enabled: "auto",
    fileName: "rabi-sound-workspace.json",
  },
  toolbar: {
    history: true,
    radar: false,
    theme: false,
    zoom: false,
  },
});
